=== Hyp3ri0n/PAI_Server/PAI_Server/interfaces/cabinet_schema.xsd
<?xml version="1.0"?>

<xsd:schema version="1.0"
           targetNamespace="http://www.ujf-grenoble.fr/cabinet"
           xmlns="http://www.ujf-grenoble.fr/cabinet"
           xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xsd:element name="cabinet" type="Cabinet"/>
    
    <xsd:complexType name="Cabinet">
        <xsd:sequence>
            <xsd:element name="nom" type="xsd:string"/>
            <xsd:element name="adresse" type="Adresse"/>
            <xsd:element name="infirmiers" type="Infirmiers"/>
            <xsd:element name="patients" type="Patients"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="Adresse">
        <xsd:sequence>
            <xsd:element name="etage" type="xsd:int" minOccurs="0"/>
            <xsd:element name="numero" type="Numero" minOccurs="0"/>
            <xsd:element name="rue" type="xsd:string"/>
            <xsd:element name="codePostal" type="CodePostal"/>
            <xsd:element name="ville" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:simpleType name="Numero">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\d{1,}(bis){0,1}"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="CodePostal">
        <xsd:restriction base="xsd:int">
            <xsd:pattern value="\d{5}"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:complexType name="Infirmiers">
        <xsd:sequence>
            <xsd:element name="infirmier" type="Infirmier" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="Infirmier">
        <xsd:sequence>
            <xsd:element name="nom" type="xsd:string"/>
            <xsd:element name="prenom" type="xsd:string"/>
            <xsd:element name="photo" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="Patients">
        <xsd:sequence>
            <xsd:element name="patient" type="Patient" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="Patient">
        <xsd:sequence>
            <xsd:element name="nom" type="xsd:string"/>
            <xsd:element name="prenom" type="xsd:string"/>
            <xsd:element name="sexe" type="Sexe"/>
            <xsd:element name="naissance" type="xsd:date"/>
            <xsd:element name="numSecu" type="NumSecu"/>
            <xsd:element name="adresse" type="Adresse"/>
            <xsd:element name="visites" type="Visites"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:simpleType name="Sexe">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="M|F"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="NumSecu">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-3]\d{14}"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:complexType name="Visites">
        <xsd:sequence>
            <xsd:element name="visite" type="Visite" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="Visite">
        <xsd:sequence>
            <xsd:element name="acte" type="Acte" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="date" type="xsd:date" use="required"/>
        <xsd:attribute name="intervenant" type="xsd:int" use="optional"/>
    </xsd:complexType>
    
    <xsd:complexType name="Acte">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="id" type="xsd:int" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    
</xsd:schema>

=== Hyp3ri0n/PAI_Server/PAI_Server/data/cabinet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 
    xmlns="http://www.ujf-grenoble.fr/cabinet"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ujf-grenoble.fr/cabinet cabinet_schema.xsd"
    -->
<cabinet>
    
    <nom>Soins à Grenoble</nom>
    <adresse>
        <numero>60</numero>
        <rue>Rue de la chimie</rue>
        <codePostal>38400</codePostal>
        <ville>St Martin d'Hères</ville>
    </adresse>
    <infirmiers>
        <infirmier id="001">
            <nom>Frechie</nom>
            <prenom>Sarah</prenom>
            <photo>sarah.png</photo>
        </infirmier>
        <infirmier id="002">
            <nom>Sticki</nom>
            <prenom>Sophie</prenom>
            <photo>sophie.png</photo>
        </infirmier>
        <infirmier id="003">
            <nom>Ochon</nom>
            <prenom>Paul</prenom>
            <photo>paul.png</photo>
        </infirmier>
    </infirmiers>
    <patients>
        <patient>
            <nom>Alécole</nom>
            <prenom>Yvon</prenom>
            <sexe>M</sexe>
            <naissance>1998-08-22</naissance>
            <numSecu>198082205545843</numSecu>
            <adresse>
                <etage>6</etage>
                <numero>46</numero>
                <rue>Avenue Felix viallet</rue>
                <codePostal>38031</codePostal>
                <ville>Grenoble</ville>
            </adresse>
            <visites>
                <visite date="2015-12-08" intervenant="001"> 
                    <acte id="109"/>
                    <acte id="300"/><!-- rien -->
                </visite>
            </visites>
        </patient>
        <patient>
            <nom>Orouge</nom>
            <prenom>Elvire</prenom>
            <sexe>F</sexe>
            <naissance>1982-03-08</naissance>
            <numSecu>282036902305218</numSecu>
            <adresse>
                <rue>Rond-Point de la Croix de Vie</rue>
                <codePostal>38700</codePostal>
                <ville>La Tronche</ville>
            </adresse>
            <visites>
                <visite date="2015-12-08" intervenant="001"><!-- <visite date="2015-12-08"> -->
                    <acte id="300"/>
                    <acte id="109"/><!-- rien -->
                    <acte id="109"/><!-- rien -->
                </visite>
            </visites>
        </patient>
        <patient>
            <nom>Pien</nom>
            <prenom>Oscare</prenom>
            <sexe>F</sexe>
            <naissance>1975-03-25</naissance>
            <numSecu>275037306569202</numSecu>
            <adresse>
                <rue>Rue Casamir Brenier</rue>
                <codePostal>38000</codePostal>
                <ville>Grenoble</ville>
            </adresse>
            <visites>
                <visite date="2015-12-08" intervenant="002"><!-- <visite date="2015-12-08"> -->
                    <acte id="101"/>
                </visite>
            </visites>
        </patient>
        <patient>
            <nom>Kapoëtla</nom>
            <prenom>Xavier</prenom>
            <sexe>M</sexe>
            <naissance>2011-08-02</naissance>
            <numSecu>111083306303521</numSecu>
            <adresse>
                <numero>25</numero>
                <rue>Avenue des Martyrs</rue>
                <codePostal>38000</codePostal>
                <ville>Grenoble</ville>
            </adresse>
            <visites>
                <visite date="2015-12-08" intervenant="002"><!-- <visite date="2015-12-08"> -->
                    <acte id="111"/>
                </visite>
            </visites>
        </patient>
    </patients>
</cabinet>
